openapi: 3.0.1
info:
  title: Clientes API
  description: "API encargada de dar altas, bajas, eliminar y modificar los clientes\
    \ de una BD."
  contact:
    name: Diego
    url: https://github.com/DiegoRSX/
    email: diegor922345@gmail.com
  license:
    name: Apache 2.0
    url: http://foo.bar
  version: "1.0"
servers:
- url: http://localhost:8080
  description: Generated server url
tags:
- name: Servicios de los clientes
  description: Controlador encargado del crud completo de los clientes.
paths:
  /api/cliente/updateCliente:
    put:
      tags:
      - Servicios de los clientes
      description: Servicio encargado de modificar un cliente de la BD.
      operationId: updateUsers
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cliente'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /api/cliente/createCliente:
    post:
      tags:
      - Servicios de los clientes
      description: Servicio encargado de insertar nuevos clientes en la BD.
      operationId: createCliente
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cliente'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /api/cliente/listAll:
    get:
      tags:
      - Servicios de los clientes
      description: Servicio encargado de listar todos los clientes en la BD.
      operationId: getAllClientes
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /api/cliente/getById/{id}:
    get:
      tags:
      - Servicios de los clientes
      description: Servicio encargado de listar un cliente por id.
      operationId: getById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
  /api/cliente/borrarCliente/{id}:
    delete:
      tags:
      - Servicios de los clientes
      description: Servicio encargado de eliminar un cliente de la BD.
      operationId: borrarCliente
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
components:
  schemas:
    Cliente:
      required:
      - email
      - lastName
      - name
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        lastName:
          type: string
        direction:
          type: string
        phoneNumber:
          type: string
        email:
          type: string
